package entity.behavior

enum class EntityAction {
    ATTACK_PLAYER,
    ATTACK_RANDOM_HOSTILE,
    CHATTER,
    FIND_ANY_WEAPON,
    FIND_EMPTY_ROOM,
    FIND_WEAPON,
    GET_ARMOR,
    GET_RANDOM_BETTER_ARMOR,
    GET_RANDOM_BETTER_WEAPON,
    GET_RANDOM_ITEM,
    GET_WEAPON,
    HEAL_SELF,
    IDLE,
    KNEEL,
    MOVE,
    NONE,
    SEARCH_RANDOM_UNSEARCHED_DEAD_HOSTILE,
    SIT,
    STAND,
}