package engine.entity.behavior

enum class EntityAction {
    ATTACK_PLAYER,
    ATTACK_RANDOM_HOSTILE,
    CHATTER,
    FIND_AND_EQUIP_ANY_WEAPON,
    FIND_AND_EQUIP_ANY_ARMOR,
    GET_RANDOM_BETTER_ARMOR,
    GET_RANDOM_BETTER_WEAPON,
    GET_RANDOM_ITEM,
    HEAL_SELF,
    LOOK,
    IDLE,
    KNEEL,
    MOVE,
    SEARCH_RANDOM_UNSEARCHED_DEAD_HOSTILE,
    SIT,
    STAND,
    GET_VALUABLE_ITEM,
    GET_ANY_ITEM
}